kind: Service
apiVersion: v1
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  selector:
    app: shipping
  ports:
    - port: 8080
      name: http
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: shipping
spec:
  selector:
    matchLabels:
      app: shipping
  replicas: 1
  template:
    metadata:
      annotations: 
        sidecar.istio.io/inject: "true"      
      labels:
        app: shipping
        version: v1
    spec:
      containers:
      - name: creditcard
        image: samuelpereiradesouza/shipping:1
        ports:
        - containerPort: 8080
      restartPolicy: Always
---