openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8089/shipping'
    description: Generated server url
paths:
  '/consulta/{cep}':
    get:
      tags:
        - shipping-controller
      operationId: findShipping
      parameters:
        - name: cep
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ShippingVO'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    ShippingVO:
      type: object
      properties:
        shippingCost:
          type: number
          format: double
        deliveryEstimated:
          type: integer
          format: int32
